# Generated by Django 2.0.5 on 2020-03-29 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('daysrequired', models.IntegerField()),
                ('suggested_season', models.CharField(max_length=100)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('Photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
