# Generated by Django 2.1.5 on 2020-03-30 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='email',
        ),
        migrations.AddField(
            model_name='advisor',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
